In [3]:
import pandas as pd
import numpy as np
import librosa
import librosa.display
from numpy import argmax
import matplotlib.pyplot as plt
%matplotlib inline
import IPython.display
import random
import warnings
import os
from PIL import Image
import pathlib
import csv



In [4]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv('four_raga.csv')
df.head()


filename  chroma_stft  chroma_cqt  chroma_cens  spectral_contrast      rmse  \
0    1.wav     0.255603    0.411835     0.255329          23.316300  0.085069   
1   10.wav     0.241670    0.399765     0.244654          23.775806  0.113857   
2   11.wav     0.239753    0.398725     0.243043          23.415107  0.124076   
3   12.wav     0.256487    0.415271     0.245733          23.575878  0.114452   
4   13.wav     0.256861    0.428064     0.253183          23.489445  0.105791   

   spectral_centroid  spectral_bandwidth      rolloff  zero_crossing_rate  \
0         669.906926          508.741177  1133.861275            0.048886   
1         786.492555          556.739951  1332.192317            0.060800   
2         636.953105          488.077231  1044.226009            0.045032   
3         662.279047          506.424321  1090.835799            0.047482   
4         712.169809          534.091768  1188.003987            0.052376   

   ...    mfcc12    mfcc13    mfcc14     mfcc15     mfcc16     mfcc17  \
0  ...  7.179214 -8.591133 -3.253313   6.194870  -6.616531 -10.687120   
1  ...  5.010662 -7.491447  4.013158   9.317725 -11.686604 -11.678240   
2  ...  4.784718 -6.212992 -1.412664   5.785853  -7.779786 -11.983498   
3  ...  3.396442 -7.554090 -1.345006   5.911909  -7.515524 -10.843798   
4  ...  4.435695 -3.489069  5.603341  10.900502  -6.715989 -10.067760   

     mfcc18    mfcc19    mfcc20    label  
0  1.931708  2.071558 -3.345204  kalyani  
1  3.731367 -3.703391 -9.171062  kalyani  
2 -0.668069 -2.400475 -7.801817  kalyani  
3 -0.261944 -3.208460 -7.055369  kalyani  
4  1.676529 -3.200789 -9.293708  kalyani  

[5 rows x 31 columns]

In [6]:
#all preprocessing
# Dropping unneccesary columns
df = df.drop(['filename'],axis=1)



In [7]:
y = df['label']
X=df.drop(['label'],axis=1)

In [8]:

X, y = make_classification(n_samples=203, n_features=30,n_classes=4, n_clusters_per_class=4,n_informative=4)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [10]:

scaler = MinMaxScaler()
scaler.fit(X_test)
scaler.fit(X_train)

MinMaxScaler()

In [11]:
X_test= scaler.transform(X_test)
X_train=scaler.transform(X_train)


In [12]:
encoder= LabelEncoder()
encoder.fit(y_test)
encoder.fit(y_train)

LabelEncoder()

In [13]:
y_test=encoder.transform(y_test)
y_train=encoder.transform(y_train)


In [14]:
y_train

array([2, 1, 0, 1, 1, 0, 1, 1, 0, 2, 3, 2, 2, 2, 3, 1, 2, 2, 3, 3, 1, 1,
       3, 3, 3, 0, 0, 2, 0, 1, 3, 0, 0, 1, 1, 0, 2, 3, 1, 0, 3, 0, 2, 0,
       0, 0, 3, 2, 3, 3, 0, 0, 2, 3, 1, 3, 3, 1, 2, 1, 0, 1, 0, 1, 3, 3,
       3, 0, 0, 2, 2, 0, 3, 0, 2, 2, 1, 2, 1, 2, 1, 1, 2, 3, 3, 2, 3, 2,
       0, 1, 0, 2, 2, 1, 0, 1, 0, 1, 2, 2, 0, 3, 3, 2, 2, 1, 2, 1, 3, 1,
       3, 2, 0, 0, 0, 2, 1, 3, 1, 3, 1, 1, 3, 1, 2, 2, 1, 3, 1, 1, 3, 3,
       1, 0, 1, 0, 1, 3, 0, 1, 2, 2], dtype=int64)

In [16]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=1000,max_depth=5)
model.fit(X_train, y_train)


RandomForestClassifier(max_depth=5, n_estimators=1000)

In [17]:

pred = model.predict(X_test)


In [18]:
pred

array([3, 3, 1, 2, 2, 3, 0, 1, 3, 0, 1, 0, 3, 1, 3, 1, 1, 2, 1, 2, 3, 1,
       1, 2, 2, 0, 1, 3, 2, 2, 2, 1, 1, 1, 1, 0, 1, 0, 3, 3, 0, 2, 3, 0,
       3, 0, 0, 0, 0, 1, 3, 2, 0, 0, 2, 2, 1, 1, 3, 2, 2], dtype=int64)

In [19]:
#Random Forest with 70:30 with out hyperparameter tunning
accuracy = accuracy_score(y_test, pred)
print('Accuracy: %.3f' % (accuracy*100))
accuracy

Accuracy: 73.770


0.7377049180327869

In [20]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.71      0.53      0.61        19
           1       0.56      1.00      0.71        10
           2       0.80      0.75      0.77        16
           3       0.93      0.81      0.87        16

    accuracy                           0.74        61
   macro avg       0.75      0.77      0.74        61
weighted avg       0.77      0.74      0.74        61



In [21]:
# number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# number of features at every split
max_features = ['auto', 'sqrt']

# max depth
max_depth = [int(x) for x in np.linspace(100, 500, num = 11)]
max_depth.append(None)
# create random grid
random_grid = {
 'n_estimators': n_estimators,
 'max_features': max_features,
 'max_depth': max_depth
 }
# Random search of parameters
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=1) 
rfc_random = RandomizedSearchCV(estimator = model, param_distributions = random_grid, n_iter = 100, cv = skf, verbose=2, random_state=42, n_jobs = -1)
# Fit the model
rfc_random.fit(X_train, y_train)
# print results
print(rfc_random.best_params_)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   15.7s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  2.8min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  6.2min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed: 15.4min finished


{'n_estimators': 1600, 'max_features': 'auto', 'max_depth': 220}


In [23]:
rfc = RandomForestClassifier(n_estimators=1600, max_depth=220, max_features='auto')
rfc.fit(X_train,y_train)
rfc_predict = rfc.predict(X_test)
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, rfc_predict))

=== Confusion Matrix ===
[[12  5  1  1]
 [ 0 10  0  0]
 [ 4  0 12  0]
 [ 0  3  1 12]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.75      0.63      0.69        19
           1       0.56      1.00      0.71        10
           2       0.86      0.75      0.80        16
           3       0.92      0.75      0.83        16

    accuracy                           0.75        61
   macro avg       0.77      0.78      0.76        61
weighted avg       0.79      0.75      0.76        61

